<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use App\Scopes\ScopePerson;

class Person extends Model
{
    //
  public function getData()
  {
    return $this -> id.':'.$this -> name.'('.$this -> age.')';
  }

  /* has One */
  /*public function board()
  {
    return $this -> hasOne('App\Board');
  }*/
  /* has One */

  /* has Many */
  /*public function boards()
  {
    return $this -> hasMany('App\Board');
  }*/
  /* has Many */

  /* belongsTo 外部から主へ Board.phpへ */

  /*
  public function scopeNameEqual( $query, $str )
  {
    return $query -> where( 'name', $str );
  }

  public function scopeAgeGreaterThan( $query, $n )
  {
    return $query -> where( 'age', '>=', $n );
  }

  public function scopeAgeLessThan( $query, $n )
  {
    return $query -> where( 'age', '<=', $n );
  }

  protected static function boot ()
  {
    parent::boot(); // TODO: Change the autogenerated stub

    static::addGlobalScope(new ScopePerson);
  }
  */

  protected $guarded = array('id');

  public static $rules = array(
    'name' => 'required',
    'mail' => 'email',
    'age' => 'integer|min:0|max:150'
  );
}
